//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavikTeste.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.PWebServiceSoap")]
    public interface PWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name prefixText from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompletionListEmpresa", ReplyAction="*")]
        HavikTeste.ServiceReference1.GetCompletionListEmpresaResponse GetCompletionListEmpresa(HavikTeste.ServiceReference1.GetCompletionListEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetCompletionListEmpresa", ReplyAction="*")]
        System.IAsyncResult BeginGetCompletionListEmpresa(HavikTeste.ServiceReference1.GetCompletionListEmpresaRequest request, System.AsyncCallback callback, object asyncState);
        
        HavikTeste.ServiceReference1.GetCompletionListEmpresaResponse EndGetCompletionListEmpresa(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompletionListEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompletionListEmpresa", Namespace="http://tempuri.org/", Order=0)]
        public HavikTeste.ServiceReference1.GetCompletionListEmpresaRequestBody Body;
        
        public GetCompletionListEmpresaRequest() {
        }
        
        public GetCompletionListEmpresaRequest(HavikTeste.ServiceReference1.GetCompletionListEmpresaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCompletionListEmpresaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prefixText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int count;
        
        public GetCompletionListEmpresaRequestBody() {
        }
        
        public GetCompletionListEmpresaRequestBody(string prefixText, int count) {
            this.prefixText = prefixText;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompletionListEmpresaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompletionListEmpresaResponse", Namespace="http://tempuri.org/", Order=0)]
        public HavikTeste.ServiceReference1.GetCompletionListEmpresaResponseBody Body;
        
        public GetCompletionListEmpresaResponse() {
        }
        
        public GetCompletionListEmpresaResponse(HavikTeste.ServiceReference1.GetCompletionListEmpresaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCompletionListEmpresaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HavikTeste.ServiceReference1.ArrayOfString GetCompletionListEmpresaResult;
        
        public GetCompletionListEmpresaResponseBody() {
        }
        
        public GetCompletionListEmpresaResponseBody(HavikTeste.ServiceReference1.ArrayOfString GetCompletionListEmpresaResult) {
            this.GetCompletionListEmpresaResult = GetCompletionListEmpresaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PWebServiceSoapChannel : HavikTeste.ServiceReference1.PWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCompletionListEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCompletionListEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HavikTeste.ServiceReference1.ArrayOfString Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HavikTeste.ServiceReference1.ArrayOfString)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PWebServiceSoapClient : System.ServiceModel.ClientBase<HavikTeste.ServiceReference1.PWebServiceSoap>, HavikTeste.ServiceReference1.PWebServiceSoap {
        
        private BeginOperationDelegate onBeginGetCompletionListEmpresaDelegate;
        
        private EndOperationDelegate onEndGetCompletionListEmpresaDelegate;
        
        private System.Threading.SendOrPostCallback onGetCompletionListEmpresaCompletedDelegate;
        
        public PWebServiceSoapClient() {
        }
        
        public PWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetCompletionListEmpresaCompletedEventArgs> GetCompletionListEmpresaCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HavikTeste.ServiceReference1.GetCompletionListEmpresaResponse HavikTeste.ServiceReference1.PWebServiceSoap.GetCompletionListEmpresa(HavikTeste.ServiceReference1.GetCompletionListEmpresaRequest request) {
            return base.Channel.GetCompletionListEmpresa(request);
        }
        
        public HavikTeste.ServiceReference1.ArrayOfString GetCompletionListEmpresa(string prefixText, int count) {
            HavikTeste.ServiceReference1.GetCompletionListEmpresaRequest inValue = new HavikTeste.ServiceReference1.GetCompletionListEmpresaRequest();
            inValue.Body = new HavikTeste.ServiceReference1.GetCompletionListEmpresaRequestBody();
            inValue.Body.prefixText = prefixText;
            inValue.Body.count = count;
            HavikTeste.ServiceReference1.GetCompletionListEmpresaResponse retVal = ((HavikTeste.ServiceReference1.PWebServiceSoap)(this)).GetCompletionListEmpresa(inValue);
            return retVal.Body.GetCompletionListEmpresaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HavikTeste.ServiceReference1.PWebServiceSoap.BeginGetCompletionListEmpresa(HavikTeste.ServiceReference1.GetCompletionListEmpresaRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCompletionListEmpresa(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCompletionListEmpresa(string prefixText, int count, System.AsyncCallback callback, object asyncState) {
            HavikTeste.ServiceReference1.GetCompletionListEmpresaRequest inValue = new HavikTeste.ServiceReference1.GetCompletionListEmpresaRequest();
            inValue.Body = new HavikTeste.ServiceReference1.GetCompletionListEmpresaRequestBody();
            inValue.Body.prefixText = prefixText;
            inValue.Body.count = count;
            return ((HavikTeste.ServiceReference1.PWebServiceSoap)(this)).BeginGetCompletionListEmpresa(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HavikTeste.ServiceReference1.GetCompletionListEmpresaResponse HavikTeste.ServiceReference1.PWebServiceSoap.EndGetCompletionListEmpresa(System.IAsyncResult result) {
            return base.Channel.EndGetCompletionListEmpresa(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HavikTeste.ServiceReference1.ArrayOfString EndGetCompletionListEmpresa(System.IAsyncResult result) {
            HavikTeste.ServiceReference1.GetCompletionListEmpresaResponse retVal = ((HavikTeste.ServiceReference1.PWebServiceSoap)(this)).EndGetCompletionListEmpresa(result);
            return retVal.Body.GetCompletionListEmpresaResult;
        }
        
        private System.IAsyncResult OnBeginGetCompletionListEmpresa(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string prefixText = ((string)(inValues[0]));
            int count = ((int)(inValues[1]));
            return this.BeginGetCompletionListEmpresa(prefixText, count, callback, asyncState);
        }
        
        private object[] OnEndGetCompletionListEmpresa(System.IAsyncResult result) {
            HavikTeste.ServiceReference1.ArrayOfString retVal = this.EndGetCompletionListEmpresa(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCompletionListEmpresaCompleted(object state) {
            if ((this.GetCompletionListEmpresaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCompletionListEmpresaCompleted(this, new GetCompletionListEmpresaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCompletionListEmpresaAsync(string prefixText, int count) {
            this.GetCompletionListEmpresaAsync(prefixText, count, null);
        }
        
        public void GetCompletionListEmpresaAsync(string prefixText, int count, object userState) {
            if ((this.onBeginGetCompletionListEmpresaDelegate == null)) {
                this.onBeginGetCompletionListEmpresaDelegate = new BeginOperationDelegate(this.OnBeginGetCompletionListEmpresa);
            }
            if ((this.onEndGetCompletionListEmpresaDelegate == null)) {
                this.onEndGetCompletionListEmpresaDelegate = new EndOperationDelegate(this.OnEndGetCompletionListEmpresa);
            }
            if ((this.onGetCompletionListEmpresaCompletedDelegate == null)) {
                this.onGetCompletionListEmpresaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCompletionListEmpresaCompleted);
            }
            base.InvokeAsync(this.onBeginGetCompletionListEmpresaDelegate, new object[] {
                        prefixText,
                        count}, this.onEndGetCompletionListEmpresaDelegate, this.onGetCompletionListEmpresaCompletedDelegate, userState);
        }
    }
}
